apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spinnaker
  namespace: spinnaker
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - spinnaker.unysolar.com
        - gate.unysolar.com
      secretName: spinnaker-tls
  rules:
    - host: spinnaker.unysolar.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spin-deck
                port:
                  number: 80
    - host: gate.unysolar.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spin-gate
                port:
                  number: 80
